### PR TITLE
allow SRPM build without scl-utils-build installed

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by ibotty** [comment]
Thank you! It's building fine on centos now (not on fedora though).

**Comment by praiskup** [comment]
Fedora is different story ... there's different scl-utils package version.  Packaging for both version of scl-utils is sort of advanced task;  worth debugging on your box (in mock) rather than in copr.

**Comment by praiskup** [comment]
Example (not necessarily good one) of SCLs for both Fedora/EPEL is now here https://copr.fedorainfracloud.org/coprs/g/db-sig/sclo-postgresql96

**Comment by ibotty** [comment]
Thank you! I'll have a look.

**Pull request merged**
